apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuberchatter-api
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kuberchatter-api
    spec:
      containers:
        - image: zergov/kuberchatter-api:latest
          imagePullPolicy: Always
          name: kuberchatter-api
          ports:
            - containerPort: 5000
